export const SN_SHOP = 'shop'
export const SHOP_TOKEN_CHANGED = SN_SHOP + '/TOKEN_CHANGED'
export const SHOP_UPDATED = SN_SHOP + '/SHOP_UPDATED'
export const SHOP_TOKEN_UPDATED= SN_SHOP + '/SHOP_TOKEN_UPDATED'