name: Run build tests

'on':  
  push:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Generate .env file
      run: cp .env.example .env
    - name: Build
      run: |
        npm run build
        npm run buildScript 